/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "MessageBus.h"
#include <memory>

//==============================================================================
/**
*/
class MidiManagerAudioProcessorEditor  : public AudioProcessorEditor, public EventListener
{
private:
    NSViewComponent nsviewComponent;
    std::shared_ptr<MessageBus> bus;
    int currentWidth = 941;
    int currentHeight = 599;
    
public:
    MidiManagerAudioProcessorEditor (MidiManagerAudioProcessor* ownerFilter);
    ~MidiManagerAudioProcessorEditor();
    void onEvent(const Event& event);

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    void resized();


};


#endif  // PLUGINEDITOR_H_INCLUDED
